//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> idPen { get; set; }
        public Nullable<int> idCustomer { get; set; }
    
        public virtual Pen Pen { get; set; }
        public virtual Сustomer Сustomer { get; set; }
    }
}
